unit uNIPremApplics;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  Qrctrls, QuickRpt, ExtCtrls, StdCtrls;

type
  TfNIPremApplics = class(TForm)
    qrNIDetail2: TQuickRep;
    QRBand1: TQRBand;
    lDetailHeader2: TQRLabel;
    QRShape49: TQRShape;
    QRShape57: TQRShape;
    QRLabel33: TQRLabel;
    QRShape60: TQRShape;
    QRShape61: TQRShape;
    QRShape62: TQRShape;
    QRShape63: TQRShape;
    QRShape64: TQRShape;
    QRShape65: TQRShape;
    QRShape66: TQRShape;
    QRShape67: TQRShape;
    QRShape71: TQRShape;
    QRShape72: TQRShape;
    QRShape73: TQRShape;
    QRShape74: TQRShape;
    QRShape75: TQRShape;
    QRShape76: TQRShape;
    QRLabel34: TQRLabel;
    QRLabel35: TQRLabel;
    QRLabel36: TQRLabel;
    QRLabel37: TQRLabel;
    QRLabel38: TQRLabel;
    QRLabel39: TQRLabel;
    QRLabel40: TQRLabel;
    QRLabel41: TQRLabel;
    QRLabel42: TQRLabel;
    QRLabel43: TQRLabel;
    QRLabel45: TQRLabel;
    QRLabel46: TQRLabel;
    QRLabel57: TQRLabel;
    QRLabel59: TQRLabel;
    QRLabel60: TQRLabel;
    QRLabel61: TQRLabel;
    QRLabel32: TQRLabel;
    QRShape45: TQRShape;
    QRLabel1: TQRLabel;
    Titleb: TQRLabel;
    Nameb: TQRLabel;
    SurNameb: TQRLabel;
    NIAddress1b: TQRLabel;
    NIAddress2b: TQRLabel;
    NIAddress3b: TQRLabel;
    HerdNob: TQRLabel;
    qrDetail2: TQRBand;
    QRShape95: TQRShape;
    QRShape96: TQRShape;
    QRShape97: TQRShape;
    QRShape98: TQRShape;
    QRShape100: TQRShape;
    QRShape101: TQRShape;
    QRShape102: TQRShape;
    QRShape103: TQRShape;
    QRShape104: TQRShape;
    QRShape105: TQRShape;
    QRShape106: TQRShape;
    QRShape107: TQRShape;
    QRShape109: TQRShape;
    QRDBText20: TQRDBText;
    QRDBText21: TQRDBText;
    QRDBText22: TQRDBText;
    QRDBText23: TQRDBText;
    QRDBText25: TQRDBText;
    QRDBText26: TQRDBText;
    QRDBText27: TQRDBText;
    QRDBText28: TQRDBText;
    QRDBText29: TQRDBText;
    QRDBText30: TQRDBText;
    QRDBText31: TQRDBText;
    QRDBText32: TQRDBText;
    QRShape108: TQRShape;
    QRShape93: TQRShape;
    QRShape94: TQRShape;
    QRDBText19: TQRDBText;
    QRShape99: TQRShape;
    QRDBText24: TQRDBText;
    QRBand3: TQRBand;
    qr4: TQRShape;
    QRLabel2: TQRLabel;
    l3: TQRLabel;
    l1: TQRLabel;
    l2: TQRLabel;
    lTot: TQRLabel;
    lTick: TQRImage;
    qrNIDetail: TQuickRep;
    QRBand4: TQRBand;
    QRShape141: TQRShape;
    lDetailHeader: TQRLabel;
    QRShape137: TQRShape;
    QRShape138: TQRShape;
    QRShape156: TQRShape;
    QRShape139: TQRShape;
    QRShape167: TQRShape;
    QRLabel102: TQRLabel;
    QRShape136: TQRShape;
    QRLabel82: TQRLabel;
    QRLabel90: TQRLabel;
    QRShape142: TQRShape;
    QRShape143: TQRShape;
    QRShape144: TQRShape;
    QRShape145: TQRShape;
    QRShape146: TQRShape;
    QRShape147: TQRShape;
    QRShape148: TQRShape;
    QRShape149: TQRShape;
    QRShape151: TQRShape;
    QRShape152: TQRShape;
    QRShape155: TQRShape;
    QRShape157: TQRShape;
    QRShape158: TQRShape;
    QRShape160: TQRShape;
    QRShape161: TQRShape;
    QRShape162: TQRShape;
    QRShape163: TQRShape;
    QRShape164: TQRShape;
    QRShape165: TQRShape;
    QRShape166: TQRShape;
    QRShape168: TQRShape;
    QRShape169: TQRShape;
    QRShape170: TQRShape;
    QRShape171: TQRShape;
    QRLabel91: TQRLabel;
    QRLabel92: TQRLabel;
    QRLabel93: TQRLabel;
    QRLabel94: TQRLabel;
    QRLabel95: TQRLabel;
    QRLabel96: TQRLabel;
    QRLabel97: TQRLabel;
    QRLabel98: TQRLabel;
    QRLabel99: TQRLabel;
    QRLabel100: TQRLabel;
    QRLabel101: TQRLabel;
    QRLabel103: TQRLabel;
    QRLabel105: TQRLabel;
    QRLabel106: TQRLabel;
    QRLabel107: TQRLabel;
    QRLabel108: TQRLabel;
    QRLabel109: TQRLabel;
    QRLabel111: TQRLabel;
    QRLabel113: TQRLabel;
    QRLabel114: TQRLabel;
    QRLabel115: TQRLabel;
    QRLabel116: TQRLabel;
    QRLabel117: TQRLabel;
    QRLabel118: TQRLabel;
    QRLabel119: TQRLabel;
    QRShape172: TQRShape;
    QRShape173: TQRShape;
    QRShape174: TQRShape;
    QRShape175: TQRShape;
    QRLabel112: TQRLabel;
    Titlea: TQRLabel;
    Namea: TQRLabel;
    SurNamea: TQRLabel;
    NIAddress1a: TQRLabel;
    NIAddress2a: TQRLabel;
    NIAddress3a: TQRLabel;
    HerdNoa: TQRLabel;
    QRShape150: TQRShape;
    qrDetail: TQRBand;
    QRShape9: TQRShape;
    QRShape10: TQRShape;
    QRShape17: TQRShape;
    QRShape28: TQRShape;
    QRShape30: TQRShape;
    QRShape31: TQRShape;
    QRShape43: TQRShape;
    QRShape48: TQRShape;
    QRShape51: TQRShape;
    QRShape52: TQRShape;
    QRShape53: TQRShape;
    QRShape54: TQRShape;
    QRShape55: TQRShape;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRDBText7: TQRDBText;
    QRDBText8: TQRDBText;
    QRDBText9: TQRDBText;
    QRDBText11: TQRDBText;
    QRDBText13: TQRDBText;
    QRDBText14: TQRDBText;
    QRDBText15: TQRDBText;
    QRDBText16: TQRDBText;
    QRDBText17: TQRDBText;
    QRDBText18: TQRDBText;
    QRShape47: TQRShape;
    QRDBText12: TQRDBText;
    QRShape3: TQRShape;
    QRShape38: TQRShape;
    QRDBText10: TQRDBText;
    QRShape56: TQRShape;
    qrNIPremium: TQuickRep;
    qrSectionA: TQRBand;
    QRShape116: TQRShape;
    QRShape131: TQRShape;
    QRShape119: TQRShape;
    QRShape128: TQRShape;
    QRShape126: TQRShape;
    QRShape125: TQRShape;
    QRShape124: TQRShape;
    QRShape127: TQRShape;
    QRLabel358: TQRLabel;
    QRLabel359: TQRLabel;
    lPremTypeContainer: TQRShape;
    QRShape113: TQRShape;
    QRMemo3: TQRMemo;
    QRMemo4: TQRMemo;
    QRMemo5: TQRMemo;
    QRLabel333: TQRLabel;
    QRLabel321: TQRLabel;
    QRLabel73: TQRLabel;
    QRLabel75: TQRLabel;
    QRLabel76: TQRLabel;
    QRLabel77: TQRLabel;
    QRShape114: TQRShape;
    QRLabel287: TQRLabel;
    QRLabel283: TQRLabel;
    QRLabel242: TQRLabel;
    QRShape123: TQRShape;
    QRLabel288: TQRLabel;
    QRLabel247: TQRLabel;
    Title: TQRLabel;
    QRLabel290: TQRLabel;
    FirstName: TQRLabel;
    QRLabel291: TQRLabel;
    Surname: TQRLabel;
    QRLabel289: TQRLabel;
    QRLabel293: TQRLabel;
    QRLabel292: TQRLabel;
    NIAddress1: TQRLabel;
    NIAddress3: TQRLabel;
    TelNumber: TQRLabel;
    NIAddress4: TQRLabel;
    NIAddress2: TQRLabel;
    QRLabel296: TQRLabel;
    QRLabel294: TQRLabel;
    HerdNum: TQRLabel;
    QRLabel297: TQRLabel;
    QRShape122: TQRShape;
    QRLabel298: TQRLabel;
    QRShape129: TQRShape;
    QRLabel301: TQRLabel;
    QRLabel300: TQRLabel;
    QRLabel302: TQRLabel;
    QRLabel352: TQRLabel;
    QRMemo6: TQRMemo;
    QRShape130: TQRShape;
    QRLabel308: TQRLabel;
    QRLabel309: TQRLabel;
    QRShape117: TQRShape;
    QRLabel310: TQRLabel;
    QRLabel312: TQRLabel;
    QRLabel311: TQRLabel;
    QRLabel313: TQRLabel;
    QRLabel314: TQRLabel;
    QRShape121: TQRShape;
    QRShape120: TQRShape;
    QRShape118: TQRShape;
    QRShape115: TQRShape;
    QRLabel335: TQRLabel;
    lMainHeader: TQRLabel;
    QRLabel361: TQRLabel;
    QRMemo2: TQRMemo;
    QRMemo1: TQRMemo;
    lPremType: TQRLabel;
    desc: TQRLabel;
    lRetentionDate: TQRLabel;
    lFarmSurveyNo: TQRLabel;
    lClientRefNo: TQRLabel;
    QRLabel334: TQRLabel;
    qrSectionC: TQRBand;
    QRLabel71: TQRLabel;
    QRLabel228: TQRLabel;
    QRLabel229: TQRLabel;
    QRLabel677: TQRLabel;
    QRLabel678: TQRLabel;
    QRLabel231: TQRLabel;
    QRMemo7: TQRMemo;
    lAType: TQRLabel;
    QRLabel80: TQRLabel;
    QRLabel81: TQRLabel;
    LWhichType: TQRLabel;
    QRLabel83: TQRLabel;
    QRLabel84: TQRLabel;
    QRMemo8: TQRMemo;
    QRLabel85: TQRLabel;
    QRMemo9: TQRMemo;
    QRLabel86: TQRLabel;
    QRMemo10: TQRMemo;
    QRLabel87: TQRLabel;
    QRMemo11: TQRMemo;
    QRLabel88: TQRLabel;
    QRMemo12: TQRMemo;
    QRLabel89: TQRLabel;
    QRMemo13: TQRMemo;
    QRLabel254: TQRLabel;
    lClaim: TQRLabel;
    QRLabel256: TQRLabel;
    QRLabel257: TQRLabel;
    QRLabel258: TQRLabel;
    QRLabel253: TQRLabel;
    QRLabel259: TQRLabel;
    QRLabel260: TQRLabel;
    QRMemo14: TQRMemo;
    QRMemo15: TQRMemo;
    QRShape135: TQRShape;
    QRLabel275: TQRLabel;
    QRLabel681: TQRLabel;
    QRLabel278: TQRLabel;
    QRLabel279: TQRLabel;
    QRLabel280: TQRLabel;
    QRLabel277: TQRLabel;
    QRLabel72: TQRLabel;
    QRLabel78: TQRLabel;
    QRShape134: TQRShape;
    QRLabel201: TQRLabel;
    QRLabel204: TQRLabel;
    QRLabel206: TQRLabel;
    QRLabel210: TQRLabel;
    QRLabel213: TQRLabel;
    QRLabel216: TQRLabel;
    QRLabel222: TQRLabel;
    QRLabel200: TQRLabel;
    QRLabel202: TQRLabel;
    QRLabel205: TQRLabel;
    QRLabel207: TQRLabel;
    QRLabel211: TQRLabel;
    QRLabel214: TQRLabel;
    QRLabel217: TQRLabel;
    QRLabel223: TQRLabel;
    QRLabel226: TQRLabel;
    QRLabel221: TQRLabel;
    QRLabel218: TQRLabel;
    QRLabel215: TQRLabel;
    QRLabel212: TQRLabel;
    QRLabel209: TQRLabel;
    QRLabel208: TQRLabel;
    QRLabel203: TQRLabel;
    Titlec: TQRLabel;
    Namec: TQRLabel;
    SurNamec: TQRLabel;
    NIAddress1c: TQRLabel;
    NIAddress2c: TQRLabel;
    NIAddress3c: TQRLabel;
    HerdNoc: TQRLabel;
    QRExpr1: TQRExpr;
    QRExpr2: TQRExpr;
    QRExpr3: TQRExpr;
    QRExpr4: TQRExpr;
    QRLabel5: TQRLabel;
    QRMemo16: TQRMemo;
    LPostcode: TQRLabel;
    QRMemo17: TQRMemo;
    QRMemo18: TQRMemo;
    QRLabel6: TQRLabel;
    QRLabel7: TQRLabel;
    LHerdNum: TQRLabel;
    lBarNum: TQRLabel;
    QRShape1: TQRShape;
    QRShape2: TQRShape;
    QRShape4: TQRShape;
    QRShape5: TQRShape;
    QRShape6: TQRShape;
    QRLabel12: TQRLabel;
    QRShape7: TQRShape;
    QRShape8: TQRShape;
    QRShape11: TQRShape;
    QRShape12: TQRShape;
    QRShape15: TQRShape;
    QRLabel4: TQRLabel;
    QRBand2: TQRBand;
    QRLabel17: TQRLabel;
    QRLabel13: TQRLabel;
    QRLabel3: TQRLabel;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRLabel9: TQRLabel;
    QRLabel14: TQRLabel;
    QRShape16: TQRShape;
    QRLabel15: TQRLabel;
    QRLabel16: TQRLabel;
    QRShape18: TQRShape;
    QRLabel8: TQRLabel;
    procedure FormCreate(Sender: TObject);
    procedure LPostcodePrint(sender: TObject; var Value: String);
    procedure qrDetail2BeforePrint(Sender: TQRCustomBand;
      var PrintBand: Boolean);
    procedure lClientRefNoPrint(sender: TObject; var Value: String);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  fNIPremApplics: TfNIPremApplics;

implementation
uses
   uApplications;

{$R *.DFM}


{ TfNIApplics }

procedure TfNIPremApplics.FormCreate(Sender: TObject);
begin
   qrNIPremium.DataSet := fApplications.PremTable;

end;

procedure TfNIPremApplics.LPostcodePrint(sender: TObject;
  var Value: String);
begin
   if value = 'LPostcode' then
      value := '';
end;

procedure TfNIPremApplics.qrDetail2BeforePrint(Sender: TQRCustomBand;
  var PrintBand: Boolean);
begin
   if fApplications.PremTable.RecordCount > 29 then
      begin
         lTick.Enabled := True;
         lTick.Visible := True;
      end
   else
      begin
         lTick.Enabled := False;
         lTick.Visible := False;
      end;
end;

procedure TfNIPremApplics.lClientRefNoPrint(sender: TObject;
  var Value: String);
begin
   if Value = TQRLabel(Sender).Caption then
      TQRLabel(Sender).Caption := '';
end;

end.
